### PR TITLE
Align SB smoke test image with servlet containers

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by pavolloffay** [comment]
The undertow tests seems to be flaky

```
UndertowInstrumentationTest > postUrlEncoded() FAILED
    org.opentest4j.AssertionFailedError at UndertowInstrumentationTest.java:113
```

cc) @ryandens

**Comment by ryandens** [comment]
> The undertow tests seems to be flaky
> 
> ```
> UndertowInstrumentationTest > postUrlEncoded() FAILED
>     org.opentest4j.AssertionFailedError at UndertowInstrumentationTest.java:113
> ```
> 
> cc) @ryandens

Thanks! I noticed this as well, still trying to zero in on the source of the flakiness, but working on this in the background. I have a suspicion that it's a thread-safety issue with how that test utilizes the in-memory exporter, so at least it doesn't seem to be an inconsistency issue with the production agent code 🤞

**Comment by pavolloffay** [comment]
on JDK8 it fails randomly.

```
while ./gradlew clean :instrumentation:undertow:undertow-1.4:test; do :; done
```

**Comment by pavolloffay** [comment]
>  I have a suspicion that it's a thread-safety issue with how that test utilizes the in-memory exporter, so at least it doesn't seem to be an inconsistency issue with the production agent code crossed_fingers

I would not be so sure bc spans are reported but the body attribute is missing.

**Comment by ryandens** [comment]
> > I have a suspicion that it's a thread-safety issue with how that test utilizes the in-memory exporter, so at least it doesn't seem to be an inconsistency issue with the production agent code crossed_fingers
> 
> I would not be so sure bc spans are reported but the body attribute is missing.

Huh, interesting. Where are you seeing that? The test failure you posted (and that I've seen as well) shows the assertion in line 113 failing which is just asserting the size of the traces list? Do the logs show the trace reported without the body attribute? Or did you get a test failure with a different assertion error?

**Comment by pavolloffay** [comment]
I get failures in my editor on line 117 ass well :/ 

```
    assertEquals(
        "{\"echo\": \"bar\"}",
        spanData.getAttributes().get(HypertraceSemanticAttributes.HTTP_RESPONSE_BODY));
```

**Comment by ryandens** [comment]
Thanks! I hadn't gotten that one yet, but this will definitely help

**Comment by pavolloffay** [comment]
The failing line 117 is my bad, wrongly initialized classpath in IDE, here is the fix for the flaky test https://github.com/hypertrace/javaagent/pull/331

**Pull request merged**
