### PR TITLE
Remove CCI and add release GHA release workflow

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/hypertrace/hypertrace/issues/144

Remove deprecated CCI release job to GHA.

I haven't tested if the credentials are correct, hence this PR might need some more love after is merged and release triggered.

### CODE REVIEW

**Comment by ryandens** [comment]
Nit: could you also update the badge in the README to point to GHA rather than CircleCI? Additionally, I believe the bullet points describing how to add an SSH key for CircleCI in [RELEASE.md#Configuration](https://github.com/hypertrace/javaagent/blob/main/RELEASE.md#configuration) are no longer necessary and can be deleted. Mainly, I'm just looking to cleanup references to CircleCI.

**Review by ryandens — APPROVED** [review]

**Comment by pavolloffay** [comment]
I will update docs, however I don't have the secrets for the local dry run. Would you like to try it yourself?

**Comment by ryandens** [comment]
> I will update docs, however I don't have the secrets for the local dry run. Would you like to try it yourself?

I don't think I'll have the time to get to it today, and I wrote this suggestion before seeing your message about cutting a patch release to test it out, that's probably a better way to go! Thanks for the PR 😃

**Comment by pavolloffay** [comment]
I will merge, cut the release, and hope 😅

**Pull request merged**
