### PR TITLE
Delete docker login from GHA

### PR DESCRIPTION
**Pull request by samarth-gupta-traceable**
## Description
Delete docker login from GHA for forks PR to work

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

### CODE REVIEW

**Review by JBAhire — APPROVED** [review]

**Comment by pavolloffay** [comment]
> merged 1 commit into main from delete_docker_login 3 hours ago

it would be better to make a PR from a branch to verify it actually works

**Comment by pavolloffay** [comment]
or there are no other issues with PRs

**Comment by JBAhire** [comment]
Hey @pavolloffay , this smoke test doesn't require docker login, Samarth added it yesterday under some speculations about test failure. And the workflow is green as well: https://github.com/hypertrace/javaagent/runs/1932599058?check_suite_focus=true

**Comment by pavolloffay** [comment]
What I am saying is that this PR should have been made from a fork to validate the use-case

**Pull request merged**
